#!/usr/bin/env python3
"""Render a static preview of the Dashboard watch face without the Connect IQ simulator.

The colour palette and the vertical layout fractions are read straight out of
``source/Theme.mc`` at run time, so this script cannot drift away from the face
the way a hand-copied table would. Everything else here is a deliberate mock:

* The Garmin system fonts are proprietary. They are approximated with DejaVu Sans
  Bold and a per-font size table calibrated by eye against the simulator.
* The sample data (weather, graph trace, step count, ...) is fixed, see SAMPLE.
* MIP anti-aliasing is approximated by rendering large and box-filtering down.

What it *does* get right: the geometry is a line-by-line mirror of
``source/DashboardView.mc`` / ``Arcs.mc`` / ``Graph.mc`` / ``Icons.mc``, it runs
at the real pixel resolution of each target device, and for the transflective
(MIP) devices it snaps every pixel to the 64-colour palette the panel can
actually show -- so colours that would dither on the watch look dithered here.

Usage::

    python3 tools/preview.py                              # preview.png, fenix8solar47mm
    python3 tools/preview.py out.png
    python3 tools/preview.py --device fenix8solar51mm out.png
    python3 tools/preview.py --scale 3 out.png            # 3x nearest-neighbour zoom
    python3 tools/preview.py --sleep out.png              # burn-in / sleep variant
    python3 tools/preview.py --no-quantize out.png        # skip the MIP palette snap
    python3 tools/preview.py --all                        # every device -> tools/preview-<device>.png
"""

import argparse
import math
import os
import re
import sys

from PIL import Image, ImageDraw, ImageFont

HERE = os.path.dirname(os.path.abspath(__file__))
THEME_MC = os.path.join(HERE, os.pardir, "source", "Theme.mc")

# --- target devices ---------------------------------------------------------
# (width, height, panel).  "mip" = transflective 64-colour memory-in-pixel.
# These are the devices in manifest.xml; the face derives everything from the
# screen size, so previewing both is a check that nothing is pinned to 260.
# The clock bitmap font is one fixed size, so it is only really right on the
# 260 px device until resources-round-280x280/fonts/ is added.
DEVICES = {
    "fenix8solar47mm": (260, 260, "mip"),
    "fenix8solar51mm": (280, 280, "mip"),
}
DEFAULT_DEVICE = "fenix8solar47mm"

FONT_CANDIDATE_PATHS = [
    "/usr/share/fonts/truetype/dejavu/DejaVuSans-Bold.ttf",
    "/usr/share/fonts/dejavu/DejaVuSans-Bold.ttf",
    "/Library/Fonts/Arial Bold.ttf",
    "/System/Library/Fonts/Supplemental/Arial Bold.ttf",
]

# The face uses two fixed Garmin system fonts (source/DashboardView.mc): XTINY
# for the date / weather / battery rows, TINY for Body Battery, steps and the
# badge number. These are their approximate pixel heights on a 260 px screen,
# scaled to the real screen at run time. DejaVu stands in for the glyphs.
XTINY_260 = 18
TINY_260 = 22

# The clock is the Chivo bitmap font from resources/fonts/, generated by
# make_clock_font.py at this em size (for 260 px) and weight; mirror both here.
CLOCK_TTF = os.path.join(HERE, "fonts", "Chivo[wght].ttf")
CLOCK_EM_260 = 95
CLOCK_WEIGHT = 700

SUPERSAMPLE = 4  # render this many times larger, then filter down

# Fixed sample readings the mock draws.
SAMPLE = {
    "date": "Thu 3 Sep",
    "temp": "27°",
    "precip": "40%",
    "condition": 0,  # Icons.SUN
    "high": "21°",
    "low": "4°",
    "graph": [58, 61, 55, None, 62, 66, 72, 95, 90, 88, 92, 87, 91, 86,
              89, 84, 88, 83, 86, 78, 74, 70, 66, 63, 60, 62, 64, 61, 59],
    "graph_is_percentage": False,
    "hours": "11",
    "minutes": "29",
    "clock_24h": True,     # True: gap on the centre line. False: block centred.
    "hour_color": None,    # None -> Theme default (white); or a T[...] key
    "minute_color": None,  # None -> Theme default (cyan)
    "body_battery": 35,
    "dnd": True,
    "alarm": True,
    "steps": "6.8k",
    "battery_days": "12d",
    "battery_pct": "64%",
    "notifications": 1,
    "arc_body_battery": 0.62,
    "arc_device_battery": 0.64,
    "arc_daylight": 0.40,
}


# --- source/Theme.mc -------------------------------------------------------
def parse_theme(path):
    """Pull every ``const NAME as T = VALUE;`` out of Theme.mc.

    Theme.mc holds two modules (Theme, Layout) whose constant names do not
    collide, so a flat dict is enough.  Handles hex (0x..), float and int
    literals and ignores trailing ``// comments``.
    """
    with open(path) as fh:
        text = fh.read()
    out = {}
    for m in re.finditer(r"const\s+(\w+)\s+as\s+[\w.<>]+\s*=\s*([^;]+);", text):
        name = m.group(1)
        raw = m.group(2).split("//")[0].strip()
        if re.fullmatch(r"0x[0-9A-Fa-f]+", raw):
            out[name] = int(raw, 16)
        elif re.fullmatch(r"-?\d+\.\d+", raw):
            out[name] = float(raw)
        elif re.fullmatch(r"-?\d+", raw):
            out[name] = int(raw)
    return out


T = parse_theme(THEME_MC)


def rgb(value):
    return ((value >> 16) & 0xFF, (value >> 8) & 0xFF, value & 0xFF)


# Colours (source/Theme.mc, module Theme)
BACKGROUND = rgb(T["BACKGROUND"])
DATE = rgb(T["DATE"])
HOURS = rgb(T["HOURS"])
MINUTES = rgb(T["MINUTES"])
TEXT = rgb(T["TEXT"])
TEXT_DIM = rgb(T["TEXT_DIM"])
SEPARATOR = rgb(T["SEPARATOR"])
GRAPH = rgb(T["GRAPH"])
OFF = rgb(T["OFF"])
DND_ON = rgb(T["DND_ON"])
ALARM_ON = rgb(T["ALARM_ON"])
NOTIFICATION_ON = rgb(T["NOTIFICATION_ON"])
ARC_BODY_BATTERY = rgb(T["ARC_BODY_BATTERY"])
ARC_DEVICE_BATTERY = rgb(T["ARC_DEVICE_BATTERY"])
ARC_DAYLIGHT = rgb(T["ARC_DAYLIGHT"])
ARC_TRACK = rgb(T["ARC_TRACK"])
ARC_TRACK_PEN = T["ARC_TRACK_PEN"]
ARC_FILL_PEN = T["ARC_FILL_PEN"]
ARC_EDGE_INSET = T["ARC_EDGE_INSET"]

# Layout fractions (source/Theme.mc, module Layout)
DATE_Y = T["DATE_Y"]
SEP_1_Y = T["SEP_1_Y"]
WEATHER_Y = T["WEATHER_Y"]
SEP_2_Y = T["SEP_2_Y"]
GRAPH_TOP_Y = T["GRAPH_TOP_Y"]
GRAPH_BOTTOM_Y = T["GRAPH_BOTTOM_Y"]
SEP_3_Y = T["SEP_3_Y"]
TIME_Y = T["TIME_Y"]
SEP_4_Y = T["SEP_4_Y"]
STATUS_Y = T["STATUS_Y"]
SEP_5_Y = T["SEP_5_Y"]
BATTERY_Y = T["BATTERY_Y"]
SEPARATOR_RADIUS = T["SEPARATOR_RADIUS"]
ARC_LEFT_FROM = T["ARC_LEFT_FROM"]
ARC_LEFT_TO = T["ARC_LEFT_TO"]
ARC_CENTER = T["ARC_CENTER"]
ARC_CENTER_SPREAD = T["ARC_CENTER_SPREAD"]
ARC_RIGHT_FROM = T["ARC_RIGHT_FROM"]
ARC_RIGHT_TO = T["ARC_RIGHT_TO"]


def find_font_path():
    for path in FONT_CANDIDATE_PATHS:
        if os.path.exists(path):
            return path
    raise SystemExit(
        "no usable TrueType font found. Install one, e.g.\n"
        "  sudo apt-get install fonts-dejavu-core\n"
        "or edit FONT_CANDIDATE_PATHS at the top of this script."
    )


FONT_PATH = find_font_path()
_font_cache = {}


def font(px, family="ui"):
    """`px` is a screen-pixel height; the returned face is SUPERSAMPLE times
    that, since all drawing happens on the supersampled canvas.

    family "ui"    - DejaVu, standing in for the Garmin system fonts
    family "clock" - the real Chivo used for the bitmap clock font, so the
                     preview clock matches what make_clock_font.py bakes
    """
    key = (family, int(px))
    if key not in _font_cache:
        if family == "clock" and os.path.exists(CLOCK_TTF):
            f = ImageFont.truetype(CLOCK_TTF, max(1, int(px * SUPERSAMPLE)))
            try:
                f.set_variation_by_axes([CLOCK_WEIGHT])
            except Exception:
                pass
        else:
            # DejaVu's cap height sits a little low; 0.80 lands close to Garmin.
            f = ImageFont.truetype(FONT_PATH, max(1, int(px * 0.80 * SUPERSAMPLE)))
        _font_cache[key] = f
    return _font_cache[key]


# --- the renderer --------------------------------------------------------
class Face:
    """One rendered face.  The drawing methods mirror source/DashboardView.mc;
    coordinates are in screen pixels and scaled up by SUPERSAMPLE on the way to
    Pillow."""

    def __init__(self, device):
        self.w, self.h, self.panel = DEVICES[device]
        self.device = device
        self.cx = self.w / 2
        self.cy = self.h / 2
        self.radius = min(self.w, self.h) / 2
        self.s = SUPERSAMPLE
        self.img = Image.new("RGB", (self.w * self.s, self.h * self.s), BACKGROUND)
        self.d = ImageDraw.Draw(self.img)

        # source/DashboardView.mc onLayout(): two fixed system fonts + the
        # Chivo bitmap clock, all scaled from their 260 px values.
        scale = self.h / 260.0
        self.clock_font = CLOCK_EM_260 * scale
        self.date_font = self.weather_font = self.small_font = XTINY_260 * scale
        self.row_font = self.badge_font = TINY_260 * scale

    # -- primitives (Pillow, supersampled) --------------------------------
    def _xy(self, *vals):
        return [v * self.s for v in vals]

    def line(self, x1, y1, x2, y2, color, width=1):
        self.d.line(self._xy(x1, y1, x2, y2), fill=color, width=max(1, int(width * self.s)))

    def rect(self, x, y, w, h, color):
        self.d.rectangle(self._xy(x, y, x + w, y + h), fill=color)

    def circle(self, x, y, r, color):
        self.d.ellipse(self._xy(x - r, y - r, x + r, y + r), fill=color)

    def ring(self, x, y, r, color, width):
        self.d.ellipse(self._xy(x - r, y - r, x + r, y + r),
                       outline=color, width=max(1, int(width * self.s)))

    def polygon(self, points, color):
        self.d.polygon([c * self.s for p in points for c in p], fill=color)

    def rounded(self, x, y, w, h, rad, color, filled=True, width=1):
        box = self._xy(x, y, x + w, y + h)
        if filled:
            self.d.rounded_rectangle(box, radius=rad * self.s, fill=color)
        else:
            self.d.rounded_rectangle(box, radius=rad * self.s, outline=color,
                                     width=max(1, int(width * self.s)))

    def arc(self, x, y, r, color, garmin_start, garmin_end, width):
        """drawArc: Garmin measures degrees counter-clockwise from 3 o'clock,
        Pillow clockwise, so negate and sort."""
        box = self._xy(x - r, y - r, x + r, y + r)
        a, b = sorted((-garmin_start, -garmin_end))
        self.d.arc(box, start=a, end=b, fill=color, width=max(1, int(width * self.s)))

    def stroke_arc(self, x, y, r, color, garmin_start, garmin_end, width):
        self.arc(x, y, r, color, garmin_start, garmin_end, width)

    def text(self, x, y, px, string, color, align="left", valign="middle", family="ui"):
        f = font(px, family)
        box = self.d.textbbox((0, 0), string, font=f)
        tw, th = box[2] - box[0], box[3] - box[1]
        ox = x * self.s
        oy = y * self.s
        if align == "center":
            ox -= tw / 2
        elif align == "right":
            ox -= tw
        if valign == "middle":
            oy -= th / 2
        self.d.text((ox - box[0], oy - box[1]), string, font=f, fill=color)

    def text_width(self, string, px, family="ui"):
        box = self.d.textbbox((0, 0), string, font=font(px, family))
        return (box[2] - box[0]) / self.s

    # -- geometry (source/DashboardView.mc) ------------------------------
    def chord(self, y):
        r = self.radius * SEPARATOR_RADIUS
        dy = y - self.cy
        sq = r * r - dy * dy
        return 0.0 if sq <= 0 else math.sqrt(sq)

    def separator(self, fraction):
        y = round(fraction * self.h)
        half = self.chord(y)
        if half < 4:
            return
        self.line(self.cx - half, y, self.cx + half, y, SEPARATOR, 1)

    # -- rows -----------------------------------------------------------
    def draw_date(self):
        self.text(self.cx, DATE_Y * self.h, self.date_font, SAMPLE["date"], DATE, align="center")

    def draw_weather(self):
        y = WEATHER_Y * self.h
        icon_r = self.w * 0.040
        pad = self.w * 0.030
        gap = self.w * 0.022
        current, precip = SAMPLE["temp"], SAMPLE["precip"]
        high, low = SAMPLE["high"], SAMPLE["low"]

        Icons.weather(self, SAMPLE["condition"], self.cx, y, icon_r, TEXT)

        edge = self.cx - icon_r - pad
        edge = self._field_right(edge, y, precip, TEXT, gap)
        self._field_right(edge, y, current, TEXT, gap)

        edge = self.cx + icon_r + pad
        edge = self._field_left(edge, y, high, TEXT, gap)
        self._field_left(edge, y, low, TEXT_DIM, gap)

    def _field_right(self, x, y, string, color, gap):
        if string is None:
            return x
        self.text(x, y, self.weather_font, string, color, align="right")
        return x - self.text_width(string, self.weather_font) - gap

    def _field_left(self, x, y, string, color, gap):
        if string is None:
            return x
        self.text(x, y, self.weather_font, string, color, align="left")
        return x + self.text_width(string, self.weather_font) + gap

    def draw_graph(self):
        top = GRAPH_TOP_Y * self.h
        bottom = GRAPH_BOTTOM_Y * self.h
        # Framed to the separator above it, less the gap above the graph.
        margin = top - SEP_2_Y * self.h
        half = self.chord(SEP_2_Y * self.h) - margin
        buckets = Graph.bucket_count(self.w, half)

        values = list(SAMPLE["graph"])
        values = (values * (buckets // len(values) + 1))[:buckets]
        Graph.draw(self, self.w, self.cx, top, bottom, values,
                   SAMPLE["graph_is_percentage"], GRAPH)

    def draw_time(self, offset_y=0.0, dim=False):
        hours, minutes = SAMPLE["hours"], SAMPLE["minutes"]
        hcol = TEXT_DIM if dim else (rgb(T[SAMPLE["hour_color"]]) if SAMPLE["hour_color"] else HOURS)
        mcol = TEXT_DIM if dim else (rgb(T[SAMPLE["minute_color"]]) if SAMPLE["minute_color"] else MINUTES)
        gap = self.w * 0.020
        y = TIME_Y * self.h + offset_y

        hours_right = self.cx - gap / 2.0
        minutes_left = self.cx + gap / 2.0
        if not SAMPLE["clock_24h"]:
            hw = self.text_width(hours, self.clock_font, "clock")
            mw = self.text_width(minutes, self.clock_font, "clock")
            left = self.cx - (hw + gap + mw) / 2.0
            hours_right = left + hw
            minutes_left = left + hw + gap

        self.text(hours_right, y, self.clock_font, hours, hcol, align="right", family="clock")
        self.text(minutes_left, y, self.clock_font, minutes, mcol, align="left", family="clock")

    def draw_status_row(self):
        y = STATUS_Y * self.h
        icon_r = self.w * 0.044
        bb = SAMPLE["body_battery"]
        self.text(self.w * 0.175, y, self.row_font,
                  "--" if bb is None else str(bb), TEXT_DIM, align="center")
        Icons.do_not_disturb(self, self.w * 0.335, y, icon_r, DND_ON if SAMPLE["dnd"] else OFF)
        Icons.alarm(self, self.cx, y, icon_r, ALARM_ON if SAMPLE["alarm"] else OFF)
        self.text(self.w * 0.775, y, self.row_font, SAMPLE["steps"], TEXT_DIM, align="center")

    def draw_battery_row(self):
        # Icons.notification spans y - 0.75r .. y + 0.85r (Icons.NOTIFICATION_SPAN);
        # grow it to fill between the separator above and the arc below, 1 px clear.
        top = SEP_5_Y * self.h + 1
        bottom = self.cy + self.radius - ARC_EDGE_INSET - ARC_FILL_PEN - 1
        radius = (bottom - top) / Icons.NOTIFICATION_SPAN * 0.95
        y = top + radius * 0.75 + 2

        count = SAMPLE["notifications"]
        Icons.notification(self, self.cx, y, radius, NOTIFICATION_ON if count > 0 else OFF)
        text_y = y - radius * 0.15
        if count > 0:
            self.text(self.cx, text_y, self.badge_font, str(count), TEXT, align="center")

        if SAMPLE["battery_days"] is not None:
            self.text(self.w * 0.32, text_y, self.small_font, SAMPLE["battery_days"], TEXT_DIM, align="center")
        self.text(self.w * 0.68, text_y, self.small_font, SAMPLE["battery_pct"], TEXT_DIM, align="center")

    def draw_arcs(self):
        Arcs.draw(self, self.cx, self.cy, self.radius,
                  SAMPLE["arc_body_battery"], SAMPLE["arc_device_battery"], SAMPLE["arc_daylight"])

    def draw_sleep_face(self):
        # source/DashboardView.mc drawSleepFace(): date + time only, dimmed,
        # nudged over a 5-minute cycle.  Preview picks one offset in that cycle.
        offset_y = -1 * (self.h / 12.0)
        self.text(self.cx, SEP_3_Y * self.h + offset_y, self.date_font,
                  SAMPLE["date"], TEXT_DIM, align="center")
        self.draw_time(offset_y, dim=True)

    # -- compose ------------------------------------------------------
    def render(self, sleep=False, quantize=True, scale=1):
        if sleep:
            self.draw_sleep_face()
        else:
            for f in (SEP_1_Y, SEP_2_Y, SEP_3_Y, SEP_4_Y, SEP_5_Y):
                self.separator(f)
            self.draw_date()
            self.draw_weather()
            self.draw_graph()
            self.draw_time()
            self.draw_status_row()
            self.draw_arcs()
            self.draw_battery_row()  # after the arcs: the badge overlaps them

        # Down to native resolution: the box filter stands in for the panel's
        # own anti-aliasing.
        out = self.img.resize((self.w, self.h), Image.BOX)

        if quantize and self.panel == "mip":
            out = mip_snap(out)

        # Round bezel mask.
        mask = Image.new("L", (self.w, self.h), 0)
        ImageDraw.Draw(mask).ellipse([0, 0, self.w - 1, self.h - 1], fill=255)
        framed = Image.new("RGB", (self.w, self.h), (18, 18, 18))
        framed.paste(out, (0, 0), mask)

        if scale != 1:
            framed = framed.resize((self.w * scale, self.h * scale), Image.NEAREST)
        return framed


# --- MIP 64-colour panel ------------------------------------------------
def mip_snap(img):
    """Snap every channel to 0x00 / 0x55 / 0xAA / 0xFF, the palette a fenix
    transflective display renders without dithering."""
    levels = [0x00, 0x55, 0xAA, 0xFF]
    lut = bytes(levels[min(3, int(round(v / 85.0)))] for v in range(256))
    return img.point(lut * 3)


# --- source/Graph.mc --------------------------------------------------
class Graph:
    MIN_BAR = 0.12

    @staticmethod
    def bar_width(w):
        return max(2, round(w * 0.0154))

    @staticmethod
    def pitch(w):
        return Graph.bar_width(w) + max(2, round(w * 0.0192))

    @staticmethod
    def bucket_count(w, half):
        return max(6, int((half * 2) / Graph.pitch(w)))

    @staticmethod
    def draw(face, w, cx, top, bottom, values, is_percentage, color):
        count = len(values)
        if count == 0:
            return
        bar = Graph.bar_width(w)
        step = Graph.pitch(w)
        total = count * step - (step - bar)
        x = round(cx - total / 2.0)      # whole-pixel origin and baseline, so
        base = round(bottom)             # every bar sits on the same line
        height = base - top

        if is_percentage:
            low, high = 0.0, 100.0
        else:
            present = [v for v in values if v is not None]
            if not present:
                return
            low, high = float(min(present)), float(max(present))
            if high - low < 0.001:
                low, high = low - 0.5, high + 0.5

        for i, value in enumerate(values):
            left = x + i * step
            if value is None:
                face.rect(left, base - 1, bar, 1, color)
                continue
            norm = min(1.0, max(0.0, (value - low) / (high - low)))
            bar_h = round(height * (Graph.MIN_BAR + (1.0 - Graph.MIN_BAR) * norm))
            face.rect(left, base - bar_h, bar, bar_h, color)


# --- source/Arcs.mc -------------------------------------------------
class Arcs:
    MIN_SWEEP = 0.75

    @staticmethod
    def clamp(f):
        return 0.0 if f < 0.0 else (1.0 if f > 1.0 else f)

    @staticmethod
    def draw(face, cx, cy, screen_r, body_battery, device_battery, daylight):
        outer = screen_r - ARC_EDGE_INSET
        r_track = outer - ARC_TRACK_PEN / 2.0
        r_fill = outer - ARC_FILL_PEN / 2.0

        for frm, to in ((ARC_LEFT_FROM, ARC_LEFT_TO),
                        (ARC_CENTER - ARC_CENTER_SPREAD, ARC_CENTER + ARC_CENTER_SPREAD),
                        (ARC_RIGHT_FROM, ARC_RIGHT_TO)):
            face.stroke_arc(cx, cy, r_track, ARC_TRACK, frm, to, ARC_TRACK_PEN)

        if body_battery is not None:
            Arcs._sweep(face, cx, cy, r_fill, ARC_BODY_BATTERY, ARC_LEFT_FROM, ARC_LEFT_TO, body_battery)

        spread = ARC_CENTER_SPREAD * Arcs.clamp(device_battery)
        if spread >= Arcs.MIN_SWEEP:
            face.stroke_arc(cx, cy, r_fill, ARC_DEVICE_BATTERY, ARC_CENTER, ARC_CENTER - spread, ARC_FILL_PEN)
            face.stroke_arc(cx, cy, r_fill, ARC_DEVICE_BATTERY, ARC_CENTER, ARC_CENTER + spread, ARC_FILL_PEN)

        if daylight is not None:
            Arcs._sweep(face, cx, cy, r_fill, ARC_DAYLIGHT, ARC_RIGHT_FROM, ARC_RIGHT_TO, daylight)

    @staticmethod
    def _sweep(face, cx, cy, radius, color, frm, to, fraction):
        length = (to - frm) * Arcs.clamp(fraction)
        if -Arcs.MIN_SWEEP < length < Arcs.MIN_SWEEP:
            return
        face.stroke_arc(cx, cy, radius, color, frm, frm + length, ARC_FILL_PEN)


# --- source/Icons.mc ----------------------------------------------
class Icons:
    SUN, PARTLY_CLOUDY, CLOUDY, RAIN, SNOW, STORM, FOG, WIND = range(8)
    NOTIFICATION_SPAN = 1.60  # source/Icons.mc

    @staticmethod
    def weather(face, group, x, y, r, color):
        if group == Icons.SUN:
            Icons._sun(face, x, y, r, color)
        elif group == Icons.PARTLY_CLOUDY:
            Icons._sun(face, x + r * 0.34, y - r * 0.36, r * 0.55, color)
            Icons._cloud(face, x - r * 0.14, y + r * 0.22, r * 0.82, color)
        elif group == Icons.CLOUDY:
            Icons._cloud(face, x, y + r * 0.1, r, color)
        elif group == Icons.RAIN:
            Icons._cloud(face, x, y - r * 0.16, r * 0.9, color)
            Icons._drops(face, x, y + r * 0.62, r, color)
        elif group == Icons.SNOW:
            Icons._cloud(face, x, y - r * 0.16, r * 0.9, color)
            Icons._flakes(face, x, y + r * 0.66, r, color)
        elif group == Icons.STORM:
            Icons._cloud(face, x, y - r * 0.2, r * 0.9, color)
            Icons._bolt(face, x, y + r * 0.6, r, color)
        elif group == Icons.FOG:
            Icons._cloud(face, x, y - r * 0.24, r * 0.82, color)
            Icons._bars(face, x, y + r * 0.58, r, color)
        elif group == Icons.WIND:
            Icons._bars(face, x, y, r * 1.25, color)

    @staticmethod
    def _sun(face, x, y, r, color):
        face.circle(x, y, r * 0.4, color)
        for i in range(8):
            a = i * math.pi / 4.0
            dx, dy = math.cos(a), math.sin(a)
            face.line(x + dx * r * 0.64, y - dy * r * 0.64, x + dx * r, y - dy * r,
                      color, max(1, round(r * 0.2)))

    @staticmethod
    def _cloud(face, x, y, r, color):
        face.circle(x - r * 0.46, y + r * 0.14, r * 0.4, color)
        face.circle(x + r * 0.44, y + r * 0.2, r * 0.36, color)
        face.circle(x - r * 0.02, y - r * 0.14, r * 0.52, color)
        face.rect(x - r * 0.86, y + r * 0.14, r * 1.72, r * 0.42, color)

    @staticmethod
    def _drops(face, x, y, r, color):
        for i in (-1, 0, 1):
            dx = x + i * r * 0.46
            face.line(dx + r * 0.1, y - r * 0.2, dx - r * 0.1, y + r * 0.24,
                      color, max(1, round(r * 0.16)))

    @staticmethod
    def _flakes(face, x, y, r, color):
        for i in (-1, 0, 1):
            face.circle(x + i * r * 0.46, y, r * 0.14, color)

    @staticmethod
    def _bolt(face, x, y, r, color):
        face.polygon([
            (x + r * 0.24, y - r * 0.42), (x - r * 0.28, y + r * 0.06),
            (x - r * 0.02, y + r * 0.06), (x - r * 0.2, y + r * 0.5),
            (x + r * 0.3, y - r * 0.04), (x + r * 0.02, y - r * 0.04),
        ], color)

    @staticmethod
    def _bars(face, x, y, r, color):
        w = max(1, round(r * 0.16))
        face.line(x - r * 0.7, y - r * 0.3, x + r * 0.7, y - r * 0.3, color, w)
        face.line(x - r * 0.5, y, x + r * 0.8, y, color, w)
        face.line(x - r * 0.7, y + r * 0.3, x + r * 0.6, y + r * 0.3, color, w)

    @staticmethod
    def do_not_disturb(face, x, y, r, color):
        face.circle(x, y - r * 0.14, r * 0.44, color)
        face.polygon([
            (x - r * 0.68, y + r * 0.42), (x - r * 0.44, y + r * 0.14),
            (x - r * 0.44, y - r * 0.14), (x + r * 0.44, y - r * 0.14),
            (x + r * 0.44, y + r * 0.14), (x + r * 0.68, y + r * 0.42),
        ], color)
        face.circle(x, y - r * 0.68, r * 0.13, color)
        face.circle(x, y + r * 0.62, r * 0.17, color)
        face.line(x - r * 0.9, y + r * 0.9, x + r * 0.9, y - r * 0.9,
                  BACKGROUND, max(1, round(r * 0.3)))
        face.line(x - r * 0.86, y + r * 0.86, x + r * 0.86, y - r * 0.86,
                  color, max(1, round(r * 0.16)))

    @staticmethod
    def alarm(face, x, y, r, color):
        stroke = max(1, round(r * 0.18))
        face.ring(x, y + r * 0.1, r * 0.66, color, stroke)
        face.line(x - r * 0.72, y - r * 0.44, x - r * 0.4, y - r * 0.72, color, stroke)
        face.line(x + r * 0.72, y - r * 0.44, x + r * 0.4, y - r * 0.72, color, stroke)
        face.line(x, y + r * 0.1, x, y - r * 0.3, color, stroke)
        face.line(x, y + r * 0.1, x + r * 0.34, y + r * 0.24, color, stroke)

    @staticmethod
    def notification(face, x, y, r, color):
        face.rounded(x - r * 0.85, y - r * 0.75, r * 1.7, r * 1.2, r * 0.30, color)
        face.polygon([(x - r * 0.24, y + r * 0.40), (x + r * 0.24, y + r * 0.40),
                      (x - r * 0.04, y + r * 0.85)], color)


# --- cli ------------------------------------------------------------
def main(argv):
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("out", nargs="?", default="preview.png", help="output PNG path")
    ap.add_argument("--device", "-d", default=DEFAULT_DEVICE, choices=sorted(DEVICES),
                    help="target device (default: %(default)s)")
    ap.add_argument("--scale", "-s", type=int, default=1,
                    help="nearest-neighbour zoom for the saved PNG (default: 1)")
    ap.add_argument("--sleep", action="store_true", help="render the sleep / burn-in variant")
    ap.add_argument("--no-quantize", dest="quantize", action="store_false",
                    help="skip the MIP 64-colour snap on transflective devices")
    ap.add_argument("--all", action="store_true",
                    help="render every device to tools/preview-<device>.png and exit")
    args = ap.parse_args(argv)

    if args.all:
        for device in sorted(DEVICES):
            path = os.path.join(HERE, "preview-%s.png" % device)
            Face(device).render(sleep=args.sleep, quantize=args.quantize,
                                scale=args.scale).save(path)
            print("wrote", path)
        return

    Face(args.device).render(sleep=args.sleep, quantize=args.quantize,
                             scale=args.scale).save(args.out)
    print("wrote %s (%s, %dx%d%s)" % (
        args.out, args.device, DEVICES[args.device][0], DEVICES[args.device][1],
        ", MIP palette" if args.quantize and DEVICES[args.device][2] == "mip" else ""))


if __name__ == "__main__":
    main(sys.argv[1:])
